### PR TITLE
Added list of technical documentation confs

### PR DESCRIPTION
**Pull request by bmansheim**

### CODE REVIEW

**Comment by nimzco** [comment]
Hey! 
I'm not sure about this list of conference, it's half docs and half content strategy conference it seems. Maybe this could be part of a `Content Strategy` section and we could add all of the conferences listed here:
https://www.prosekiln.com/blog/2017/11/7/2018-content-strategy-conferences

@prigara do you have some thoughts on that?

**Comment by bmansheim** [comment]
Hi Nima,

I made the list just from Google searches because I didn't want to piggyback on someone else's work that they are using to promote themselves.

Also, documentation is sometimes included in content strategy, UX, and support. It's a good question how to give a techcomm person a good sense of which conferences might be interesting for them out of those 3 categories. Maybe just start with the pure techcomm conferences.

Thanks

**Comment by prigara** [comment]
Hey!
I agree that it's better to start with the pure tech comm conferences like Write the Docs and then see where it goes.

**Comment by nimzco** [comment]
Awesome, than you @bmansheim, I'll merge that and publish the conferences. Thanks a bunch! 👍

**Pull request merged**
