### PR TITLE
Add a note about using Online as location for online events

### PR DESCRIPTION
**Pull request by prigara**

### CODE REVIEW

**Comment by cgrail** [comment]
It's Ok as a first step.

Eventually I would like to move to an approach where we can also handle hybrid conferences, because currently we don't support them. I'll always have to decide whether I make a conference online only or onsite.

I would suggest to add an additional attribute to conferences like ```online``` and get rid of the value ```online``` for ```city``` and ```country```. 

An online conference would then look like this:
```
{
  "name": "DrupalCon North America",
  "url": "https://events.drupal.org",
  "startDate": "2021-04-12",
  "endDate": "2021-04-16",
  "online": true
}
```

A hybrid conference would then look like this:
```
{
  "name": "JavaZone",
  "url": "http://javazone.no",
  "startDate": "2021-09-08",
  "endDate": "2021-09-09",
  "city": "Oslo",
  "country": "Norway",
  "online": true
}
```

@nimzco would you be able to help us with this? I could update the data and validators. But we would also need to update the page and server code.

**Review by cgrail — APPROVED** [review]

**Comment by prigara** [comment]
Yeah, I've also thought about hybrid events after Floor's question in [#2997](https://github.com/tech-conferences/conference-data/pull/2997). For those submitting the event it will definitely be easier to have a checkbox. For filtering and search, it might be easier to support an array of locations (checkbox in the form will add Online to locations) but I'm not sure.

**Comment by cgrail** [comment]
> For filtering and search, it might be easier to support an array of locations (checkbox in the form will add Online to locations) but I'm not sure.

I think that's doable. We should be able to support both cases. For the search I also think a checkbox would be easier for online events.

**Comment by nimzco** [comment]
Super late to the party, sorry folks. The first email notification got lost in the mass. 🙏🏼

Let's ship this and I'll add an `online` option after, I like what you're suggesting @cgrail. 
Thanks for your contributions! ❤️ 

And Happy New Year! ✨

**Review by nimzco — APPROVED** [review]

**Pull request merged**
