### PR TITLE
Add GitHubStar button

### LINKED ISSUE #648: Integrate GitHub star
Integrate GitHub star count to showcase project popularity and credibility, fostering future contributions.

1 or 2?
image

### PR DESCRIPTION
**Pull request by JuanPabloDiaz**
What do you think @nimzco and @cgrail?

Closes #648

image

### CODE REVIEW

**Comment by nimzco** [comment]
Hey @JuanPabloDiaz ! Just seeing this now.
The button is a bit floating in the middle. How about trying to place it here:
366509349-df281049-04e2-4982-9ca6-dccbac594fb0

**Comment by JuanPabloDiaz** [comment]
Ready to be merged 

image

**Comment by JuanPabloDiaz** [comment]
LGTM

**Comment by nimzco** [comment]
Nice!

**Pull request merged**
