### PR TITLE
Add Github handle of submitter

### PR DESCRIPTION
**Pull request by nimzco**

### CODE REVIEW

**Comment by prigara** [comment]
Hi @nimzco, do we need it for submissions via the form? I think some people might not have github. 🤔
We also have validation failing now: https://github.com/tech-conferences/conference-data/pull/5662

**Comment by nimzco** [comment]
@cgrail requested this new field for being able to help identify someone on GitHub. Cf: https://github.com/tech-conferences/api.confs.tech/pull/82

The field is not mandatory though, maybe we should specify it. And we can rename it as well, the current label is not the greatest 😅

**Comment by nimzco** [comment]
I've also just updated GHA: https://github.com/tech-conferences/conference-data/pull/5664

**Comment by nimzco** [comment]
And I've made sure we don't submit the field if `null`

**Comment by cgrail** [comment]
> Hi @nimzco, do we need it for submissions via the form? I think some people might not have github. 🤔

Hi @prigara 
the idea was to also store the GitHub username in case of questions regarding a submission or to inform somebody that a submission has been rejected. I rarely or almost never get any feedback/response or complains if I reject or modify a submission. An initial idea could be to ask for the e-mail address, but I wouldn't like to store that information in a json in a GitHub repo. With the e-mail address you could reach almost everybody.
The suggestion I've made is a compromise to the e-mail address. It allows us to get in touch with submitters without asking them for something private or confidential. Most developers should have a GitHub account and that's also our primary audience. The problem arises if some marketing, sales or other non-tech people start submitting entries. The problem is I don't know. 
But limiting a submission to only people with a GitHub account could also help us filter out non-dev submissions, which we get a lot.
I don't know whether this will work, but I thought it might be worth a try.

**Comment by prigara** [comment]
Hi @cgrail, thanks, good point about rejections.
How about:

Github username of submitter => Your GitHub username (optional)

and the note below:
In case we have questions about your submission

Or 

In case we need to contact your about your submission


What do you think, folks?

**Comment by cgrail** [comment]
Hi @prigara 

currently it says something like that:
Bildschirmfoto 2023-06-30 um 22 28 12

https://confs.tech/conferences/new

I would like to keep the GitHub username field optional. But just today I got 3 conferences which are not developer related like:
- [a conference for people who run a casino](https://github.com/tech-conferences/conference-data/pull/5668)
- [a conference for stem cells and tissue engineering research](https://github.com/tech-conferences/conference-data/pull/5667)
- [a conference for decarbonising America](https://events.reutersevents.com/sustainable-business/net-zero-usa)

I would like to not receive those types of conferences any longer. So far nobody has submitted their GitHub username. Even for valid developer conferences. Let's wait a few more weeks. But we need a solution for getting spammed with non-dev related conferences. I'm also open for other options.

**Comment by nimzco** [comment]
How about moving that field to the bottom of the form like that?
https://github.com/tech-conferences/confs.tech/pull/562

**Comment by cgrail** [comment]
Funny. Just now we received a PR, where somebody added his phone number as GitHub username:
https://github.com/tech-conferences/conference-data/pull/5673

People seem to have an interest about the status of the submission.

**Comment by prigara** [comment]
> I would like to not receive those types of conferences any longer. 

Let's try to update the text on top of the submission form to emphasize once again our focus on the events around software dev. I'll send a PR for review later today.

**Pull request merged**
