### PR TITLE
Removed JS conferences files and updated README

### PR DESCRIPTION
**Pull request by nimzco**
- Updated the README 
- Removed all `javascript.json` files since they are in the `javascript-conferences` repo.

@hkasera, do you think it is clear enough?

### CODE REVIEW

**Comment by hkasera** [comment]
Just a clarification, to add a new Javascript conference, we just have to create an issue right? Only to edit an existing Javascript conference, we need to send a PR. Am I correct? If yes, then may be the readme show reflect the same. Instead of saying "To add JavaScript conferences..." we should maybe say "To edit existing JavaScript conferences..."

What do you think?

**Comment by nimzco** [comment]
Ideally I would like people to send pull requests for new conferences following the structure that is in the README, that's why I just specified send a PR.

**Comment by nimzco** [comment]
I will merge this for the time being. Let me still know what you think!

**Comment by hkasera** [comment]
Looks good to me 👍 Sorry for late reply.

**Pull request merged**
