### PR TITLE
Add a banner notifying about possible changes in event dates

### PR DESCRIPTION
**Pull request by prigara**
Due to the current situation many events have been canceled or postponed. We don't track the latest status of each event in the list so it's better to warn people that some event dates might have been changed.

### CODE REVIEW

**Comment by nimzco** [comment]
Thanks for taking care of that @prigara, I had the same idea tonight..!

**Comment by nimzco** [comment]
I've tweeted the message and pinned it on the Twitter account: https://twitter.com/ConfsTech

**Comment by prigara** [comment]
@nimzco thanks! 👍
Stay safe and flatten the curve!

**Comment by nimzco** [comment]
Thank you, you too!

**Pull request merged**
