### PR TITLE
Add support for mastodon

### PR DESCRIPTION
**Pull request by hmasila**
Add Mastodon input field
Add tests for mastodon handle validity

### CODE REVIEW

**Comment by nimzco** [comment]
Hi @hmasila, thank you for your submission.

Do you know of any conferences out there with Mastodon accounts?

I'm not against adding the field, I justI worry the form becomes very long 😬

**Comment by hmasila** [comment]
@nimzco No, I don't. The PR is in reference to https://github.com/tech-conferences/conference-data/issues/5670 

The mastodon field is optional just like the github one

**Comment by FrittenLoverMarvin** [comment]
For example [Java Forum Nord](https://ijug.social/@JavaForumNord) but I will look for more examples.

**Comment by nimzco** [comment]
I have to say, I'm a little on the fence of adding this field as it seems very little used, but it won't hurt.
I'm thinking we can show it like that: 
image

I'll push a commit.

But I need to tweak the API before I can merge this PR. I'll try to take some time in the next few days to do it.

**Comment by nimzco** [comment]
Actually, might be as simple as that: https://github.com/tech-conferences/api.confs.tech/pull/88 Let's try! :)

**Comment by nimzco** [comment]
https://github.com/tech-conferences/conference-data/pull/5690 🎉

**Comment by nimzco** [comment]
Thanks for the contribution! ❤️

**Comment by FrittenLoverMarvin** [comment]
I don't see Mastodon on the frontend. 🤔
May you please check, @hmasila & @nimzco?

Example 1:

Example 2:

**Comment by nimzco** [comment]
Hi @FrittenLoverMarvin , thanks for reporting. I had forgotten to update the front-end, I wanted to see if people actually submitted mastodon social links. We've got a handful.

I'm shipping this addition right now: https://github.com/tech-conferences/confs.tech/pull/566

**Pull request merged**
