### PR TITLE
Add DevOpsDays Stockholm

### PR DESCRIPTION
**Pull request by veggiemonk**

### CODE REVIEW

**Comment by nimzco** [comment]
I feel like there are many dev ops conferences and we could maybe open a new list. What do you think?
A quick google search shows me: http://www.bmc.com/blogs/devops-conferences/

**Comment by veggiemonk** [comment]
@nimzco yes please. Let me know where I can add this entry or feel free to add it .

**Comment by nimzco** [comment]
Let me create the list quickly and link it to you.

**Comment by nimzco** [comment]
Here it is: https://github.com/tech-conferences/confs.tech/pull/169
We can close this. I'll add an issue to add more dev ops conferences

**Pull request closed without merging**
