### PR TITLE
Add product and leadership as a topic

### PR DESCRIPTION
**Pull request by nimzco**
@trivikr @prigara @cgrail are you onboard with adding _Product_ as a topic? I think it’s close enough to technologies that it would make sense to have it. 

I am thinking to do the same for _Leadership_ as well if you are onboard.

### CODE REVIEW

**Comment by cgrail** [comment]
👍 whatever Product means.

In the longterm I would like to refactor it to a more tag based approach. So that a conference can have multiple tags instead of maintaining the same conference in multiple topics.

**Comment by nimzco** [comment]
@cgrail I’m all for that, but we would probably need to do a week of hackathon to accomplish such a refactor! 😄

**Comment by nimzco** [comment]
Here is some examples of product conferences:

- https://industryconference.com/
- https://www.mindtheproduct.com/conferences/
- https://www.productschool.com/productcon/
- https://www.leadingtheproduct.com/
- https://events.productcraft.com/conference
- https://www.frontutah.com/

**Comment by trivikr** [comment]
:+1:

**Comment by nimzco** [comment]
:shipit:

**Pull request merged**
