### PR TITLE
Added discount filter

### PR DESCRIPTION
**Pull request by nimzco**
When we'll have more affiliate links, we could do something like:

discounts

cc @prigara @trivikr

### CODE REVIEW

**Comment by prigara** [comment]
Do we want to make it that visible?

**Comment by nimzco** [comment]
In one hand we don’t have much conferences with promo code. In the other hand, fake it until you make it?
Maybe we can then put a message saying: « Want to offer a discount for your conference? Contact us. »

--
Nima Izadi
+1 (514) 431-9512
nimz.co

**Comment by prigara** [comment]
> Want to offer a discount for your conference? Contact us. 
Like it :)

**Comment by cgrail** [comment]
👍

**Comment by nimzco** [comment]
I'll close this since it's not really relevant anymore.

**Pull request closed without merging**
